name = "protein-price-bot"
main = "src/index.ts"
compatibility_date = "2026-08-01"

[[d1_databases]]
binding = "DB"
database_name = "protein-price-db"
database_id = "0a80ea08-a6c5-4936-80c4-079871f4f6aa"
